### ISSUE TITLE
When srtcp is encrypted with gcm, it cannot pass the auth authentication when srtcp is decrypted?

### ISSUE THREAD

**Issue by cszdlt** [pion/srtp#136]
### Your environment.
  - Version: *v2.0.1*
  - Browser: *chrome 87.0.4280.141*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?
I use pion/webrtc to establish a connection with webrtc on the browser, and then when the browser returns rtcp information (such as nack), pion/webrtc will return an unpacking error message. After following up, it was found that the error came from the decryption verification of srtcp (srtcp.go:18). The established srtcp uses gcm encryption. I found that the SRTP_AES128_CM_HMAC_SHA1_80 encryption method has a generateSrtcpAuthTag call (srtp_cipher_aes_cm_hmac_sha1.go:138), but SRTP_AEAD_AES_128_GCM does not. Is this the cause of the problem? After I switched the encryption method of srtcp to SRTP_AES128_CM_HMAC_SHA1_80, this problem disappeared.
   --From google translation

**Comment by Sean-Der** [comment]
Thank you so much for the bug report!

I am looking into this now. Will try to resolve quickly, sorry for the delay.

**Comment by Sean-Der** [comment]
Fixed!

Mind trying new version of Pion WebRTC https://github.com/pion/webrtc/releases/tag/v3.0.14 ?

thanks for reporting this
