### ISSUE TITLE
new pion/rtp Heade is not PayloadOffset,

### ISSUE THREAD

**Issue by senlinms** [pion/srtp#147]
pion/rtp 
// Header represents an RTP packet header
type Header struct {
	Version          uint8
	Padding          bool
	Extension        bool
	Marker           bool
	PayloadType      uint8
	SequenceNumber   uint16
	Timestamp        uint32
	SSRC             uint32
	CSRC             []uint32
	ExtensionProfile uint16
	Extensions       []Extension
}
github.com/pion/srtp
../../../../srtp/session_srtp.go:144:9: assignment mismatch: 1 variable but h.Unmarshal returns 2 values
../../../../srtp/srtp.go:37:9: assignment mismatch: 1 variable but header.Unmarshal returns 2 values
../../../../srtp/srtp.go:52:9: assignment mismatch: 1 variable but header.Unmarshal returns 2 values
../../../../srtp/srtp.go:56:51: header.PayloadOffset undefined (type *rtp.Header has no field or method PayloadOffset)
../../../../srtp/srtp_cipher_aead_aes_gcm.go:99:13: header.PayloadOffset undefined (type *rtp.Header has no field or method PayloadOffset)
../../../../srtp/srtp_cipher_aead_aes_gcm.go:104:18: header.PayloadOffset undefined (type *rtp.Header has no field or method PayloadOffset)
../../../../srtp/srtp_cipher_aes_cm_hmac_sha1.go:121:30: header.PayloadOffset undefined (type *rtp.Header has no field or method PayloadOffset)
../../../../srtp/srtp_cipher_aes_cm_hmac_sha1.go:126:32: header.PayloadOffset undefined (type *rtp.Header has no field or method PayloadOffset)

**Comment by Sean-Der** [comment]
Hey @senlinms 

Sorry for the delay.

Pion uses Go Modules. The `master` branch of each repository may not work together. If you need help setting that up I am available in [Slack](https://pion.ly/slack)
