### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by madawei2699** [pion/srtp#171]
### Your environment.
  - Version: *v1.5.2*
  - Browser: *Chrome Version 95.0.4638.54 (Official Build) (x86_64)*
  - Other Information

my code: https://github.com/madawei2699/free4chat/blob/3867ee89cb44ecd3efb581598621decadbf151a1/backend/src/user.go#L102-L131 

### What did you do?

when the user disconnect unexpectedly, the webrtc peer connections close, then the memory panic has occurred. 

### What did you expect?

can normally close the peer connections

### What happened?

My app crashed!

error stack:

```
2021/11/08 10:05:36 websocket: close 1006 (abnormal closure): unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1339a42]

goroutine 64 [running]:
github.com/pion/srtp.(*ReadStreamSRTCP).Close(0x0, 0x0, 0x0)
	~/go/pkg/mod/github.com/pion/srtp@v1.5.2/stream_srtcp.go:66 +0x42
github.com/pion/webrtc/v2.(*RTPReceiver).Stop(0xc0001394a0, 0x0, 0x0)
	~/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.3/rtpreceiver.go:139 +0x105
github.com/pion/webrtc/v2.(*RTPTransceiver).Stop(0xc0002084c0, 0x4d, 0x0)
	~/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.3/rtptransceiver.go:55 +0x17b
github.com/pion/webrtc/v2.(*PeerConnection).Close(0xc00008bb00, 0x39, 0x0)
	~/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.3/peerconnection.go:1355 +0xdb
main.(*User).readPump.func1(0xc000226460)
	/tmp/free4chat/backend/src/user.go:105 +0x33
main.(*User).readPump(0xc000226460)
	/tmp/free4chat/backend/src/user.go:131 +0x3aa
created by main.serveWs
	/tmp/free4chat/backend/src/user.go:639 +0x98a
```

**Comment by Sean-Der** [comment]
This is fixed!

in v2.3.3 [received](https://github.com/pion/webrtc/blob/1f448413f22d6c32d690db594748d8ad5d3812f5/rtpreceiver.go#L69) would be closed before setting [readStreams]( https://github.com/pion/webrtc/blob/1f448413f22d6c32d690db594748d8ad5d3812f5/rtpreceiver.go#L82)

We then would call Close on the nil values [here](https://github.com/pion/webrtc/blob/1f448413f22d6c32d690db594748d8ad5d3812f5/rtpreceiver.go#L139)

in master we properly assert `!= nil` [here](https://github.com/pion/webrtc/blob/master/rtpreceiver.go#L258)

**Comment by madawei2699** [comment]
thanks！

**Comment by madawei2699** [comment]
> This is fixed!
> 
> 
> 
> in v2.3.3 [received](https://github.com/pion/webrtc/blob/1f448413f22d6c32d690db594748d8ad5d3812f5/rtpreceiver.go#L69) would be closed before setting [readStreams]( https://github.com/pion/webrtc/blob/1f448413f22d6c32d690db594748d8ad5d3812f5/rtpreceiver.go#L82)
> 
> 
> 
> We then would call Close on the nil values [here](https://github.com/pion/webrtc/blob/1f448413f22d6c32d690db594748d8ad5d3812f5/rtpreceiver.go#L139)
> 
> 
> 
> in master we properly assert `!= nil` [here](https://github.com/pion/webrtc/blob/master/rtpreceiver.go#L258)

Thanks! @Sean-Der Does it mean I need to upgrade webrtc to v3? Because webrtc v2 use srtp v1.
