### ISSUE TITLE
Fix `testRTPReplayProtection` and `testRTPLifecyleInPlace` for GCM

### ISSUE THREAD

**Issue by Sean-Der** [pion/srtp#194]
Currently these tests fail and we just `logf` the result.

[here](https://github.com/pion/srtp/blob/f94f18fcc55060e6138e319810d1ceaddf6ae954/srtp_test.go#L321) and [here](https://github.com/pion/srtp/blob/f94f18fcc55060e6138e319810d1ceaddf6ae954/srtp_test.go#L392)

**Comment by jech** [comment]
Fixed by #195

**Comment by adriancable** [comment]
#195 and #197 are now both in.
