### ISSUE TITLE
Please make ProtectionProfile methods public

### ISSUE THREAD

**Issue by sirzooro** [pion/srtp#258]
## Summary

Please make `ProtectionProfile` methods public

## Motivation

I am implementing SRTP support for my RTSP Server. I need to send key management parameters using MIKEY protocol to RTSP client. They include lengths of key, salt, etc.

## Describe alternatives you've considered

I added constants for these values to my code. Calling `ProtectionProfile` methods to get these values would result in cleaner code.

**Comment by Sean-Der** [comment]
That sounds great! Mind opening a PR?
