### ISSUE TITLE
Please ensure that NULL profiles are not negotiated by default

### ISSUE THREAD

**Issue by jech** [pion/srtp#297]
Since https://github.com/pion/dtls/commit/6178064b9f001cb10dc80d99bd66254fe273bac8, we support unencrypted profiles.  However, I do not see any code that prevents these profiles from being negotiated by default, which to my untrained eyes implies that pion-to-pion communication might end up unencrypted.

We should either remove the unencrypted profiles, or add a test that verifies that we never negotiate them without them being explicitly requested by the client.

**Comment by sirzooro** [comment]
@jech list of protection profiles used by default is elsewhere: https://github.com/pion/webrtc/blob/master/constants.go#L47

**Comment by jech** [comment]
Thanks for the info, @sirzooro.
