### ISSUE TITLE
Add AES-GCM Support

### ISSUE THREAD

**Issue by Sean-Der** [pion/srtp#85]
I am working on a benchmark to show `RTSP -> WebRTC` fanout performance. I want to land this first before getting numbers :)

This is the difference when using libsrtp, so we should see a pretty big improvement for Pion as well! This is due to be able to use hardware acceleration (Auth+Encrypt) can all be done in one step now.

```
-- aes_cm_128_hmac_sha1_32
./a.out  1.83s user 0.01s system 99% cpu 1.843 total
./a.out  1.84s user 0.01s system 99% cpu 1.856 total
./a.out  1.83s user 0.00s system 99% cpu 1.837 total
./a.out  1.82s user 0.01s system 99% cpu 1.831 total
./a.out  2.04s user 0.01s system 99% cpu 2.065 total
./a.out  1.82s user 0.01s system 99% cpu 1.834 total
./a.out  1.84s user 0.01s system 99% cpu 1.857 total
./a.out  1.83s user 0.00s system 99% cpu 1.843 total
./a.out  1.85s user 0.01s system 99% cpu 1.860 total
./a.out  1.83s user 0.01s system 99% cpu 1.839 total

-- aes_gcm_128_16
./a.out  0.76s user 0.00s system 99% cpu 0.772 total
./a.out  0.81s user 0.00s system 99% cpu 0.814 total
./a.out  0.75s user 0.00s system 99% cpu 0.762 total
./a.out  0.75s user 0.01s system 99% cpu 0.760 total
./a.out  0.76s user 0.00s system 99% cpu 0.765 total
./a.out  0.76s user 0.00s system 99% cpu 0.765 total
./a.out  0.79s user 0.01s system 99% cpu 0.803 total
./a.out  0.77s user 0.01s system 99% cpu 0.780 total
./a.out  0.75s user 0.00s system 99% cpu 0.762 total
./a.out  0.79s user 0.01s system 99% cpu 0.796 total
```

**Comment by Sean-Der** [comment]
https://tools.ietf.org/html/rfc7714 is the RFC for this

**Comment by at-wat** [comment]
Latest shares of WebRTC SRTP cipher
https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2020-07-10&include_spill=0&keys=__none__!__none__!__none__&max_channel_version=beta%252F79&measure=WEBRTC_SRTP_CIPHER&min_channel_version=beta%252F63&processType=*&product=Firefox&sanitize=0&sort_by_value=0&sort_keys=submissions&start_date=2020-06-29&table=1&trim=1&use_submission_date=0


Category | WEBRTC_SRTP_CIPHER Count
-- | --
Unknown | 0 (0%)
Aes128CmHmacSha1_80 | 6.39M (86.6%)
Aes128CmHmacSha1_32 | 143.81k (1.95%)
AeadAes128Gcm | 765.02k (10.37%)
AeadAes256Gcm | 79.05k (1.07%)

ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1491583

**Comment by Sean-Der** [comment]
@at-wat that is super cool I had no idea FireFox made these stats available!

**Comment by Sean-Der** [comment]
I have RTP done in my local tree! @jech I think you will be really interested in this since you are chasing performance :)

```
ProtectionProfileAes128CmHmacSha1_80 - BenchmarkEncryptRTP-4             636799              1706 ns/op
ProtectionProfileAeadAes128Gcm              -  BenchmarkEncryptRTP-4           2941428               403 ns/op 
```
